# © 2018 Numigi
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

{
    "name": "Main Module",
    "version": "1.0.0",
    "author": "Numigi",
    "maintainer": "Numigi",
    "website": "https://www.numigi.com",
    "license": "LGPL-3",
    "category": "Other",
    "summary": "Install all addons required for testing.",
    "depends": [
        "account_additional_group",
        "account_analytic_required_forbidden",
        "account_bank_menu",
        "account_banking_reconciliation_enhanced",
        "account_budget_balance",
        "account_check_deposit_enhanced",
        "account_closing_journal",
        "account_closing_journal_mis_builder",
        "account_closing_wizard",
        "account_fr_ca_labels",
        "account_invoice_unified_payment",
        "account_manual_entry_restricted",
        "account_move_chatter",
        "account_move_reversal_access",
        "account_move_reversed_entry",
        "account_move_unique_reversal",
        "account_negative_debit_credit",
        "account_payment_cancel_group",
        "account_payment_from_move_line",
        "account_payment_term_usage",
        "account_payment_term_usage_purchase",
        "account_payment_term_usage_sale",
        "account_payment_widget_link",
        "account_report_line_menu",
        "account_report_trial_balance",
        "account_show_full_features",
        "account_transfer_with_partner",
        "account_type_archive",
        "account_unaffected_earnings_disabled",
        "bank_reconciliation_filter",
        "bank_statement_extra_columns",
        "bank_statement_no_reverse",
        "bank_statement_online_stripe",
        "bank_statement_partner_mapping",
        "budget_analysis_account_move_line",
        "canada_account_types",
        "canada_bank_transfer",
        "hr_expense_tax_adjustment",
        "invoice_currency_validation",
        "invoice_fiscal_position_required",
        "invoice_intercompany_compatible",
        "invoice_list_email",
        "invoice_mass_mailing_with_layout",
        "invoice_refund_not_earlier",
        "invoice_write_access",
        "invoice_write_access_purchase",
        "invoice_write_access_sale",
        "mis_builder_automated_report",
        "l10n_generic_coa",  # Used for testing addons
        "old_accounts",
        "payment_stripe_not_silenced",
        "vendor_invoice_full_list",
    ],
    "installable": True,
}
