version: '3'
services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_TOKEN=${GIT_TOKEN}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./.log:/var/log/odoo
      - ./account_additional_group:/mnt/extra-addons/account_additional_group
      - ./account_analytic_required_forbidden:/mnt/extra-addons/account_analytic_required_forbidden
      - ./account_bank_menu:/mnt/extra-addons/account_bank_menu
      - ./account_closing_journal:/mnt/extra-addons/account_closing_journal
      - ./account_closing_journal_mis_builder:/mnt/extra-addons/account_closing_journal_mis_builder
      - ./account_closing_wizard:/mnt/extra-addons/account_closing_wizard
      - ./account_fr_ca_labels:/mnt/extra-addons/account_fr_ca_labels
      - ./account_show_full_features:/mnt/extra-addons/account_show_full_features
      - ../base-addons/lang_fr_activated:/mnt/extra-addons/lang_fr_activated
    ports:
      - "8069:8069"
      - "8071:8071"
    depends_on:
      - db
    command: odoo
    environment:
      - LOG_ODOO=/var/log/odoo
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    expose:
      - 5432

volumes:
  odoo-web-data:
  odoo-db-data:
